name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testing*
jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#       - name: update env
#         run: |
#           mkdir -p /home/runner/bin
#           echo 'echo "Print the PATH: $PATH"' >> printpath.sh
#           chmod +x printpath.sh
#           cp printpath.sh /home/runner/bin/
#           echo "PATH=$PATH:/home/runner/bin" >>  ${GITHUB_ENV}
#       - name: Check if env var is updated
#         run: |
#           echo $PATH
#           printpath.sh
      - name: test2
        env:
          TEST_DIR: /home/runner/wallet
        run: |
          pwd
          mkdir -p ${TEST_DIR}
          ls -l /home/runner/
          curl -Lo ${TEST_DIR}/kubectl https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl
          echo "TEST_DIR=${TEST_DIR" >> $GITHUB_ENV;
      - name: test3
        run: |
          echo ${TEST_DIR}
          ls -l ${TEST_DIR}

