name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testing*
jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: update env
        run: |
          mkdir -p /home/runner/bin
          echo "PATH=$PATH:/home/runner/bin" >>  $GITHUB_ENV
          echo "::add-mask::$SECRET_VAR"
          echo "SECRET_VAR=Supers#dcrereioed" >> $GITHUB_ENV
          echo "::add-mask::$SECRET_VAR"
          echo "SECRET_VAR2=Supers#dcrereioedxxds" >> $GITHUB_ENV
      - name: mask vars
        run: |
          
      - name: test 2
        env:
          TEST_DIR: /home/runner/wallet
        run: 
          curl -Lo ${TEST_DIR}/ "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - name: test3
        run:
          ls -l ${TEST_DIR}

