name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testing*
jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: update env
        run: |
          mkdir -p /home/runner/bin
          echo "PATH=$PATH:/home/runner/bin" >>  $GITHUB_ENV
          echo "::add-mask::$SECRET_VAR"
          echo "SECRET_VAR=Supers#dcrereioed" >> $GITHUB_ENV
          echo "::add-mask::$SECRET_VAR"
          echo "SECRET_VAR2=Supers#dcrereioedxxds" >> $GITHUB_ENV
      - name: check updated
        run: |
          echo "Secret Var is $SECRET_VAR or ${{ env.SECRET_VAR }}"
          echo "Secret Var2 is $SECRET_VAR2 or ${{ env.SECRET_VAR2 }}"


