name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testing*
jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: update env
        env:
          vars: ${{ env.ENV_VARS }}
        run: |
            echo $vars | base64 -d  > varfile.txt
            while read line 
            do
              varname=$(echo $line | cut -d "=" -f1)
              echo $varname
              echo '::add-mast::$varnanme'
            done< varfile.txt
            cat varfile.txt >> $GITHUB_ENV
      - name: check masking
        run: |
          echo $SECRET1


