name: Testing

on:
  push:
    branches:
      - main
      - test/**

jobs:
  testing
    name: update env path
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: export env var
        run: |
          mkdir -p /home/runner/bin
          echo "Print the PATH: $PATH" >> printpath.sh
          chmod +x printpath.sh
          cp printpath.sh /home/runner/bin/
          echo "PATH=$PATH:/home/runner/bin" >> ${{ GITHUB_ENV }}
      - name: Check if env var is updated
        run: |
          echo $PATH
          printpath.sh



